name: dependency-submission
on:
  push:
    branches:
      - main
jobs:
  pre-release:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup jdk11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: '(compile|runtime)Classpath'
      - name: Run mikepenz gradle-dependency-submission
        uses: mikepenz/gradle-dependency-submission@v1.0.0
        with:
            gradle-build-configuration:  |-
              runtimeOnly
