name: release
on:
  push:
    tags:
      - v*
jobs:
  pre-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup jdk11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set Version
        run: |
          sed -i "s/\(project.version=\).*/\1${GITHUB_REF#refs/*/v}/g" src/main/resources/application.properties
      - name: Build & Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: genTsTypes build
      - name: Save dist zip
        run: cp build/distributions/*.zip .
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ endsWith(GitHub.ref, 'alpha') || endsWith(GitHub.ref, 'beta') }}
          files: |
            *.zip
